### ISSUE TITLE
Scope not updating in teamwork

### ISSUE THREAD

**Issue by Wholloran** [openforge/JuntoScope#133]
When you complete a scoping session the scope is not being updated in teamwork. I tested this using my OpenForge Teamwork account with admin right. I tested this on the Startuptide task list "Sample" and on the pizzascope task lists

**Comment by Wholloran** [comment]
After running a few sessions the only task that is having its scope not be updated is the first task of each session

**Comment by Fdom92** [comment]
@Wholloran this issue is related to #134. The problem is that when the moderator clicks on continue, the session gets updated, this means the change on the title and number of task, due to this change of the session, you see reflected that on teamwork.

Let me explain:

- When we scope task 1 with 5h, on the estimate screen we are updating the session so we see the change to task 2 and the number from 1/4 to 2/4. We are sending the estimate to Teamwork before going to the next task, this means that we are sending the estimate for task 1 into the task 2 due to the mentioned change.

This happens with all tasks so thats why you don't see estimated only the first task, the fix for this is on the PR #151, i can create the fix easily after merging that PR.

**Comment by Wholloran** [comment]
After retesting with the latest build. The following is what I'm seeing: 
scope task list "new scope" from project pizza scope
Scope task 1/4 and that estimate gets applied to task 2/4 on teamwork
task 2/4 gets scoped and that scope is applied to 3/4 on teamwork
3/4 gets applied to 4/4
4/4 gets applied to 4/4 on teamwork (overriding the previous scope)

**Comment by Fdom92** [comment]
I fixed this on teamwork-auth branch

**Comment by Wholloran** [comment]
Scopes are saved as expected now, closing ticket
